### ISSUE TITLE
Address 型を GoldilocksField にする

### ISSUE THREAD

**Issue by adust09** [InternetMaximalism/intmax-zkp-core#33]
Address 型を HashOut<GoldilocksField> から GoldilocksField に変更し, PublicKey 型と区別して使用する.

https://github.com/InternetMaximalism/intmax-zkp-core/blob/ba1b6447e9e7a2cedb9f1792bb32997799a91053/src/zkdsa/account.rs#L24

(元のissue: https://github.com/InternetMaximalism/intmax-zkp/issues/49 )

**Comment by hrmk1o3** [comment]
deprecated
