### ISSUE TITLE
asset amount の型を u64 よりも大きくする

### ISSUE THREAD

**Issue by adust09** [InternetMaximalism/intmax-zkp-core#34]
F::ORDER.pow(4) までは大きくできるはず.

https://github.com/InternetMaximalism/intmax-zkp-core/blob/f3f1e9cbb04928c5628ec679a29c7efdc1adec2d/src/transaction/asset.rs#L52

(元のissue:https://github.com/InternetMaximalism/intmax-zkp/issues/48)

**Comment by hrmk1o3** [comment]
deprecated
